DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE Employee (
  ID LONG AUTO_INCREMENT  PRIMARY KEY,
  FIRSTNAME VARCHAR(250) NOT NULL,
  LASTNAME VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) DEFAULT NULL
);

INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (1, 'Bhagat', 'Singh', 'bhagat.sigh@practice.com');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (2, 'Sukhdev', 'Thapar', 'sukhdev.thapar@practice.com');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (3, 'Rajguru', 'Shivaram', 'rajguru.shivaram@practice.com');